# .github/workflows/deploy-moysoft.yml
name: Deploy moysoft website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify build
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6a0f4a5a197ebdbba5cf40f9
